/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestioncitoyen (void)
{
  GtkWidget *gestioncitoyen;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow5;
  GtkWidget *viewport9;
  GtkWidget *fixed12;
  GtkWidget *entry3;
  GtkWidget *treeview1nouha;
  GtkWidget *label16;
  GtkWidget *Supprimeraficherr;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label96;
  GtkWidget *affichernouha;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label95;
  GtkWidget *label652nouha;
  GtkWidget *affichertous;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label101;
  GtkWidget *affichercitoyen;
  GtkWidget *scrolledwindow6;
  GtkWidget *viewport8;
  GtkWidget *fixed11;
  GtkWidget *idnouha;
  GtkObject *spinbutton1nouha_adj;
  GtkWidget *spinbutton1nouha;
  GtkObject *spinbutton2nouha_adj;
  GtkWidget *spinbutton2nouha;
  GtkObject *spinbutton3nouha_adj;
  GtkWidget *spinbutton3nouha;
  GtkWidget *nomnouha;
  GtkWidget *emailnouha;
  GtkWidget *cinnouha;
  GtkWidget *telephonenouha;
  GtkWidget *matriculenouha;
  GtkWidget *marquenouha;
  GtkWidget *label26;
  GtkWidget *n12;
  GtkWidget *n4;
  GtkWidget *n3;
  GtkWidget *n2;
  GtkWidget *n1;
  GtkWidget *label_statusnouha;
  GtkWidget *ajouternouha;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label75;
  GtkWidget *radiobutton2nouha;
  GSList *radiobutton2nouha_group = NULL;
  GtkWidget *radiobutton1nouha;
  GtkWidget *label35;
  GtkWidget *n8;
  GtkWidget *n5;
  GtkWidget *n7;
  GtkWidget *checkbutton1nouha;
  GtkWidget *checkbutton2nouha;
  GtkWidget *label29;
  GtkWidget *label37;
  GtkWidget *combo1nouha;
  GtkWidget *combo2nouha;
  GtkWidget *titre1nouha;
  GtkWidget *ajoutercitoyen;
  GtkWidget *scrolledwindow7;
  GtkWidget *viewport7;
  GtkWidget *fixed13;
  GtkWidget *idnouha1;
  GtkObject *spinbutton1nouha1_adj;
  GtkWidget *spinbutton1nouha1;
  GtkObject *spinbutton2nouha1_adj;
  GtkWidget *spinbutton2nouha1;
  GtkObject *spinbutton3nouha1_adj;
  GtkWidget *spinbutton3nouha1;
  GtkWidget *nomnouha1;
  GtkWidget *emailnouha1;
  GtkWidget *cinnouha1;
  GtkWidget *telephonenouha1;
  GtkWidget *matriculenouha1;
  GtkWidget *label_statusnouha1;
  GtkWidget *label84;
  GtkWidget *n15;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *label78;
  GtkWidget *label91;
  GtkWidget *label79;
  GtkWidget *label90;
  GtkWidget *label76;
  GtkWidget *marquenouha1;
  GtkWidget *cherchernouha;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label94;
  GtkWidget *modifiernouha;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label93;
  GtkWidget *combo2nouha1;
  GtkWidget *combo1nouha1;
  GtkWidget *label85;
  GtkWidget *label80;
  GtkWidget *radiobutton2nouha1;
  GtkWidget *radiobutton1nouha1;
  GSList *radiobutton1nouha1_group = NULL;
  GtkWidget *checkbutton1nouha1;
  GtkWidget *checkbutton2nouha1;
  GtkWidget *label13;
  GtkWidget *scrolledwindow9;
  GtkWidget *viewport5;
  GtkWidget *fixed8;
  GtkWidget *anneeavance;
  GtkWidget *treeviewpaiement;
  GtkWidget *cinavance;
  GtkWidget *label72;
  GtkWidget *afficherpaiementnouha;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label97;
  GtkWidget *calculernouha;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label98;
  GtkWidget *prixnouha;
  GtkWidget *moisavance;
  GtkWidget *label70;
  GtkWidget *label100;
  GtkWidget *label15;

  gestioncitoyen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestioncitoyen), _("window3"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (gestioncitoyen), notebook1);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow5);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), scrolledwindow5,
                                      TRUE, TRUE, GTK_PACK_START);

  viewport9 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport9);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), viewport9);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (viewport9), fixed12);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed12), entry3, 192, 16);
  gtk_widget_set_size_request (entry3, 208, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  treeview1nouha = gtk_tree_view_new ();
  gtk_widget_show (treeview1nouha);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview1nouha, 0, 80);
  gtk_widget_set_size_request (treeview1nouha, 1272, 496);

  label16 = gtk_label_new (_("cin"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed12), label16, 72, 8);
  gtk_widget_set_size_request (label16, 144, 65);

  Supprimeraficherr = gtk_button_new ();
  gtk_widget_show (Supprimeraficherr);
  gtk_fixed_put (GTK_FIXED (fixed12), Supprimeraficherr, 800, 592);
  gtk_widget_set_size_request (Supprimeraficherr, 264, 64);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Supprimeraficherr), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox5), label96, FALSE, FALSE, 0);

  affichernouha = gtk_button_new ();
  gtk_widget_show (affichernouha);
  gtk_fixed_put (GTK_FIXED (fixed12), affichernouha, 456, 8);
  gtk_widget_set_size_request (affichernouha, 184, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (affichernouha), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox4), label95, FALSE, FALSE, 0);

  label652nouha = gtk_label_new (_("label96"));
  gtk_widget_show (label652nouha);
  gtk_fixed_put (GTK_FIXED (fixed12), label652nouha, 120, 592);
  gtk_widget_set_size_request (label652nouha, 664, 57);

  affichertous = gtk_button_new ();
  gtk_widget_show (affichertous);
  gtk_fixed_put (GTK_FIXED (fixed12), affichertous, 1072, 16);
  gtk_widget_set_size_request (affichertous, 200, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (affichertous), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("Afficher tout "));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox8), label101, FALSE, FALSE, 0);

  affichercitoyen = gtk_label_new (_("Afficher"));
  gtk_widget_show (affichercitoyen);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), affichercitoyen);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow6);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), scrolledwindow6,
                                      TRUE, TRUE, GTK_PACK_START);

  viewport8 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport8);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), viewport8);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (viewport8), fixed11);

  idnouha = gtk_entry_new ();
  gtk_widget_show (idnouha);
  gtk_fixed_put (GTK_FIXED (fixed11), idnouha, 168, 72);
  gtk_widget_set_size_request (idnouha, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (idnouha), 8226);

  spinbutton1nouha_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1nouha = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1nouha_adj), 1, 0);
  gtk_widget_show (spinbutton1nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton1nouha, 168, 232);
  gtk_widget_set_size_request (spinbutton1nouha, 72, 35);

  spinbutton2nouha_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2nouha = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2nouha_adj), 1, 0);
  gtk_widget_show (spinbutton2nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton2nouha, 248, 232);
  gtk_widget_set_size_request (spinbutton2nouha, 64, 35);

  spinbutton3nouha_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  spinbutton3nouha = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3nouha_adj), 1, 0);
  gtk_widget_show (spinbutton3nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton3nouha, 320, 232);
  gtk_widget_set_size_request (spinbutton3nouha, 80, 35);

  nomnouha = gtk_entry_new ();
  gtk_widget_show (nomnouha);
  gtk_fixed_put (GTK_FIXED (fixed11), nomnouha, 168, 120);
  gtk_widget_set_size_request (nomnouha, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomnouha), 8226);

  emailnouha = gtk_entry_new ();
  gtk_widget_show (emailnouha);
  gtk_fixed_put (GTK_FIXED (fixed11), emailnouha, 168, 184);
  gtk_widget_set_size_request (emailnouha, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (emailnouha), 8226);

  cinnouha = gtk_entry_new ();
  gtk_widget_show (cinnouha);
  gtk_fixed_put (GTK_FIXED (fixed11), cinnouha, 568, 120);
  gtk_widget_set_size_request (cinnouha, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinnouha), 8226);

  telephonenouha = gtk_entry_new ();
  gtk_widget_show (telephonenouha);
  gtk_fixed_put (GTK_FIXED (fixed11), telephonenouha, 576, 176);
  gtk_widget_set_size_request (telephonenouha, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (telephonenouha), 8226);

  matriculenouha = gtk_entry_new ();
  gtk_widget_show (matriculenouha);
  gtk_fixed_put (GTK_FIXED (fixed11), matriculenouha, 632, 384);
  gtk_widget_set_size_request (matriculenouha, 240, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (matriculenouha), 8226);

  marquenouha = gtk_entry_new ();
  gtk_widget_show (marquenouha);
  gtk_fixed_put (GTK_FIXED (fixed11), marquenouha, 208, 384);
  gtk_widget_set_size_request (marquenouha, 240, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (marquenouha), 8226);

  label26 = gtk_label_new (_("Cin"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed11), label26, 448, 128);
  gtk_widget_set_size_request (label26, 49, 17);

  n12 = gtk_label_new (_("Recevoir notification "));
  gtk_widget_show (n12);
  gtk_fixed_put (GTK_FIXED (fixed11), n12, 16, 456);
  gtk_widget_set_size_request (n12, 160, 16);

  n4 = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (n4);
  gtk_fixed_put (GTK_FIXED (fixed11), n4, 16, 240);
  gtk_widget_set_size_request (n4, 136, 25);

  n3 = gtk_label_new (_("Adresse_email"));
  gtk_widget_show (n3);
  gtk_fixed_put (GTK_FIXED (fixed11), n3, 0, 184);
  gtk_widget_set_size_request (n3, 160, 41);

  n2 = gtk_label_new (_("Nom complet"));
  gtk_widget_show (n2);
  gtk_fixed_put (GTK_FIXED (fixed11), n2, 0, 120);
  gtk_widget_set_size_request (n2, 136, 33);

  n1 = gtk_label_new (_("Id"));
  gtk_widget_show (n1);
  gtk_fixed_put (GTK_FIXED (fixed11), n1, 48, 80);
  gtk_widget_set_size_request (n1, 49, 17);

  label_statusnouha = gtk_label_new (_("label23"));
  gtk_widget_show (label_statusnouha);
  gtk_fixed_put (GTK_FIXED (fixed11), label_statusnouha, 712, 576);
  gtk_widget_set_size_request (label_statusnouha, 512, 65);

  ajouternouha = gtk_button_new ();
  gtk_widget_show (ajouternouha);
  gtk_fixed_put (GTK_FIXED (fixed11), ajouternouha, 512, 576);
  gtk_widget_set_size_request (ajouternouha, 184, 69);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouternouha), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox1), label75, FALSE, FALSE, 0);

  radiobutton2nouha = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton2nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton2nouha, 328, 336);
  gtk_widget_set_size_request (radiobutton2nouha, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2nouha), radiobutton2nouha_group);
  radiobutton2nouha_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2nouha));

  radiobutton1nouha = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton1nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton1nouha, 184, 336);
  gtk_widget_set_size_request (radiobutton1nouha, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1nouha), radiobutton2nouha_group);
  radiobutton2nouha_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1nouha));

  label35 = gtk_label_new (_("Matricule voiture"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed11), label35, 416, 376);
  gtk_widget_set_size_request (label35, 232, 65);

  n8 = gtk_label_new (_("Marque voiture"));
  gtk_widget_show (n8);
  gtk_fixed_put (GTK_FIXED (fixed11), n8, 0, 376);
  gtk_widget_set_size_request (n8, 216, 57);

  n5 = gtk_label_new (_("Region"));
  gtk_widget_show (n5);
  gtk_fixed_put (GTK_FIXED (fixed11), n5, 24, 280);
  gtk_widget_set_size_request (n5, 128, 49);

  n7 = gtk_label_new (_("genre"));
  gtk_widget_show (n7);
  gtk_fixed_put (GTK_FIXED (fixed11), n7, 24, 320);
  gtk_widget_set_size_request (n7, 128, 65);

  checkbutton1nouha = gtk_check_button_new_with_mnemonic (_("email "));
  gtk_widget_show (checkbutton1nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton1nouha, 208, 440);
  gtk_widget_set_size_request (checkbutton1nouha, 136, 40);

  checkbutton2nouha = gtk_check_button_new_with_mnemonic (_("SMS"));
  gtk_widget_show (checkbutton2nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), checkbutton2nouha, 376, 432);
  gtk_widget_set_size_request (checkbutton2nouha, 192, 56);

  label29 = gtk_label_new (_("numero_telephone"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed11), label29, 392, 184);
  gtk_widget_set_size_request (label29, 153, 25);

  label37 = gtk_label_new (_("Methode de paiement "));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed11), label37, 0, 504);
  gtk_widget_set_size_request (label37, 200, 25);

  combo1nouha = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo1nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), combo1nouha, 168, 296);
  gtk_widget_set_size_request (combo1nouha, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Ben Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Kebili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Sidi bou zid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Mahdia "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Medenine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Gabes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Sousse "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha), _("Gafsa"));

  combo2nouha = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo2nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), combo2nouha, 208, 496);
  gtk_widget_set_size_request (combo2nouha, 173, 45);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo2nouha), _("Especes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo2nouha), _("Carte Bancaire"));

  titre1nouha = gtk_label_new (_("salut"));
  gtk_widget_show (titre1nouha);
  gtk_fixed_put (GTK_FIXED (fixed11), titre1nouha, 0, 16);
  gtk_widget_set_size_request (titre1nouha, 736, 49);

  ajoutercitoyen = gtk_label_new (_("Ajouter"));
  gtk_widget_show (ajoutercitoyen);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), ajoutercitoyen);

  scrolledwindow7 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow7);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow7);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), scrolledwindow7,
                                      TRUE, TRUE, GTK_PACK_START);

  viewport7 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport7);
  gtk_container_add (GTK_CONTAINER (scrolledwindow7), viewport7);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (viewport7), fixed13);

  idnouha1 = gtk_entry_new ();
  gtk_widget_show (idnouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), idnouha1, 168, 168);
  gtk_widget_set_size_request (idnouha1, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (idnouha1), 8226);

  spinbutton1nouha1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1nouha1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1nouha1_adj), 1, 0);
  gtk_widget_show (spinbutton1nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton1nouha1, 168, 272);
  gtk_widget_set_size_request (spinbutton1nouha1, 72, 35);

  spinbutton2nouha1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2nouha1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2nouha1_adj), 1, 0);
  gtk_widget_show (spinbutton2nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton2nouha1, 248, 272);
  gtk_widget_set_size_request (spinbutton2nouha1, 64, 35);

  spinbutton3nouha1_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  spinbutton3nouha1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3nouha1_adj), 1, 0);
  gtk_widget_show (spinbutton3nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton3nouha1, 328, 272);
  gtk_widget_set_size_request (spinbutton3nouha1, 80, 35);

  nomnouha1 = gtk_entry_new ();
  gtk_widget_show (nomnouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), nomnouha1, 504, 176);
  gtk_widget_set_size_request (nomnouha1, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomnouha1), 8226);

  emailnouha1 = gtk_entry_new ();
  gtk_widget_show (emailnouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), emailnouha1, 168, 216);
  gtk_widget_set_size_request (emailnouha1, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (emailnouha1), 8226);

  cinnouha1 = gtk_entry_new ();
  gtk_widget_show (cinnouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), cinnouha1, 168, 104);
  gtk_widget_set_size_request (cinnouha1, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinnouha1), 8226);

  telephonenouha1 = gtk_entry_new ();
  gtk_widget_show (telephonenouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), telephonenouha1, 504, 224);
  gtk_widget_set_size_request (telephonenouha1, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (telephonenouha1), 8226);

  matriculenouha1 = gtk_entry_new ();
  gtk_widget_show (matriculenouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), matriculenouha1, 576, 416);
  gtk_widget_set_size_request (matriculenouha1, 200, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (matriculenouha1), 8226);

  label_statusnouha1 = gtk_label_new (_("Salut cher citoyen"));
  gtk_widget_show (label_statusnouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), label_statusnouha1, 784, 576);
  gtk_widget_set_size_request (label_statusnouha1, 384, 65);

  label84 = gtk_label_new (_("Methode de paiement "));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed13), label84, 0, 528);
  gtk_widget_set_size_request (label84, 200, 25);

  n15 = gtk_label_new (_("Recevoir notification "));
  gtk_widget_show (n15);
  gtk_fixed_put (GTK_FIXED (fixed13), n15, 16, 488);
  gtk_widget_set_size_request (n15, 160, 16);

  label86 = gtk_label_new (_("genre"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed13), label86, 32, 368);
  gtk_widget_set_size_request (label86, 104, 41);

  label87 = gtk_label_new (_("Region"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed13), label87, 64, 336);
  gtk_widget_set_size_request (label87, 49, 17);

  label88 = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed13), label88, 16, 280);
  gtk_widget_set_size_request (label88, 136, 25);

  label89 = gtk_label_new (_("Adresse_email"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed13), label89, 0, 208);
  gtk_widget_set_size_request (label89, 160, 41);

  label78 = gtk_label_new (_("numero_telephone"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed13), label78, 344, 224);
  gtk_widget_set_size_request (label78, 153, 25);

  label91 = gtk_label_new (_("Id"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed13), label91, 56, 168);
  gtk_widget_set_size_request (label91, 49, 17);

  label79 = gtk_label_new (_("Cin"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed13), label79, 56, 112);
  gtk_widget_set_size_request (label79, 49, 17);

  label90 = gtk_label_new (_("Nom complet"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed13), label90, 344, 160);
  gtk_widget_set_size_request (label90, 136, 33);

  label76 = gtk_label_new (_("label23"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed13), label76, 168, 24);
  gtk_widget_set_size_request (label76, 265, 57);

  marquenouha1 = gtk_entry_new ();
  gtk_widget_show (marquenouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), marquenouha1, 184, 424);
  gtk_widget_set_size_request (marquenouha1, 200, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (marquenouha1), 8226);

  cherchernouha = gtk_button_new ();
  gtk_widget_show (cherchernouha);
  gtk_fixed_put (GTK_FIXED (fixed13), cherchernouha, 352, 104);
  gtk_widget_set_size_request (cherchernouha, 176, 37);
  gtk_button_set_focus_on_click (GTK_BUTTON (cherchernouha), FALSE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (cherchernouha), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox3), label94, FALSE, FALSE, 0);

  modifiernouha = gtk_button_new ();
  gtk_widget_show (modifiernouha);
  gtk_fixed_put (GTK_FIXED (fixed13), modifiernouha, 576, 576);
  gtk_widget_set_size_request (modifiernouha, 184, 69);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifiernouha), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label93 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox2), label93, FALSE, FALSE, 0);

  combo2nouha1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo2nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), combo2nouha1, 208, 528);
  gtk_widget_set_size_request (combo2nouha1, 200, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo2nouha1), _("Especes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo2nouha1), _("Carte Bancaire"));

  combo1nouha1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combo1nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), combo1nouha1, 184, 320);
  gtk_widget_set_size_request (combo1nouha1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Ben Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Kebili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Sidi bou zid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Mahdia "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Medenine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Gabes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Sousse "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1nouha1), _("Gafsa"));

  label85 = gtk_label_new (_("Marque voiture"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed13), label85, 0, 416);
  gtk_widget_set_size_request (label85, 200, 49);

  label80 = gtk_label_new (_("Matricule voiture"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed13), label80, 392, 424);
  gtk_widget_set_size_request (label80, 184, 33);

  radiobutton2nouha1 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton2nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton2nouha1, 280, 376);
  gtk_widget_set_size_request (radiobutton2nouha1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2nouha1), radiobutton2nouha_group);
  radiobutton2nouha_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2nouha1));

  radiobutton1nouha1 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton1nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton1nouha1, 160, 376);
  gtk_widget_set_size_request (radiobutton1nouha1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1nouha1), radiobutton1nouha1_group);
  radiobutton1nouha1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1nouha1));

  checkbutton1nouha1 = gtk_check_button_new_with_mnemonic (_("email "));
  gtk_widget_show (checkbutton1nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton1nouha1, 200, 472);
  gtk_widget_set_size_request (checkbutton1nouha1, 136, 40);

  checkbutton2nouha1 = gtk_check_button_new_with_mnemonic (_("SMS"));
  gtk_widget_show (checkbutton2nouha1);
  gtk_fixed_put (GTK_FIXED (fixed13), checkbutton2nouha1, 352, 456);
  gtk_widget_set_size_request (checkbutton2nouha1, 272, 69);

  label13 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label13);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow9);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), scrolledwindow9,
                                      TRUE, TRUE, GTK_PACK_START);

  viewport5 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport5);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), viewport5);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (viewport5), fixed8);

  anneeavance = gtk_entry_new ();
  gtk_widget_show (anneeavance);
  gtk_fixed_put (GTK_FIXED (fixed8), anneeavance, 504, 592);
  gtk_widget_set_size_request (anneeavance, 192, 51);
  gtk_entry_set_invisible_char (GTK_ENTRY (anneeavance), 8226);

  treeviewpaiement = gtk_tree_view_new ();
  gtk_widget_show (treeviewpaiement);
  gtk_fixed_put (GTK_FIXED (fixed8), treeviewpaiement, 248, 152);
  gtk_widget_set_size_request (treeviewpaiement, 488, 400);

  cinavance = gtk_entry_new ();
  gtk_widget_show (cinavance);
  gtk_fixed_put (GTK_FIXED (fixed8), cinavance, 152, 64);
  gtk_widget_set_size_request (cinavance, 216, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinavance), 8226);

  label72 = gtk_label_new (_("annee"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed8), label72, 368, 600);
  gtk_widget_set_size_request (label72, 88, 33);

  afficherpaiementnouha = gtk_button_new ();
  gtk_widget_show (afficherpaiementnouha);
  gtk_fixed_put (GTK_FIXED (fixed8), afficherpaiementnouha, 384, 56);
  gtk_widget_set_size_request (afficherpaiementnouha, 208, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (afficherpaiementnouha), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox6), label97, FALSE, FALSE, 0);

  calculernouha = gtk_button_new ();
  gtk_widget_show (calculernouha);
  gtk_fixed_put (GTK_FIXED (fixed8), calculernouha, 736, 576);
  gtk_widget_set_size_request (calculernouha, 160, 80);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (calculernouha), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-media-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label98 = gtk_label_new_with_mnemonic (_("calculer"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox7), label98, FALSE, FALSE, 0);

  prixnouha = gtk_label_new (_("paiement"));
  gtk_widget_show (prixnouha);
  gtk_fixed_put (GTK_FIXED (fixed8), prixnouha, 936, 584);
  gtk_widget_set_size_request (prixnouha, 232, 65);

  moisavance = gtk_entry_new ();
  gtk_widget_show (moisavance);
  gtk_fixed_put (GTK_FIXED (fixed8), moisavance, 152, 592);
  gtk_widget_set_size_request (moisavance, 192, 51);
  gtk_entry_set_invisible_char (GTK_ENTRY (moisavance), 8226);

  label70 = gtk_label_new (_("mois"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed8), label70, 32, 600);
  gtk_widget_set_size_request (label70, 80, 33);

  label100 = gtk_label_new (_("Cin"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed8), label100, 8, 56);
  gtk_widget_set_size_request (label100, 144, 65);

  label15 = gtk_label_new (_("Historique Paiement"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label15);

  g_signal_connect ((gpointer) treeview1nouha, "cursor_changed",
                    G_CALLBACK (on_treeview1nouha_cursor_changed),
                    NULL);
  g_signal_connect ((gpointer) Supprimeraficherr, "clicked",
                    G_CALLBACK (on_Supprimeraficherr_clicked),
                    NULL);
  g_signal_connect ((gpointer) affichernouha, "clicked",
                    G_CALLBACK (on_affichernouha_clicked),
                    NULL);
  g_signal_connect ((gpointer) affichertous, "clicked",
                    G_CALLBACK (on_affichertous_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouternouha, "clicked",
                    G_CALLBACK (on_ajouternouha_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2nouha, "toggled",
                    G_CALLBACK (on_radiobutton2nouha_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1nouha, "toggled",
                    G_CALLBACK (on_radiobutton1nouha_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1nouha, "toggled",
                    G_CALLBACK (on_checkbutton1nouha_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2nouha, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) cherchernouha, "clicked",
                    G_CALLBACK (on_cherchernouha_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifiernouha, "clicked",
                    G_CALLBACK (on_modifiernouha_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2nouha1, "toggled",
                    G_CALLBACK (on_radiobutton2nouha1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1nouha1, "toggled",
                    G_CALLBACK (on_radiobutton1nouha1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1nouha1, "toggled",
                    G_CALLBACK (on_checkbutton1nouha1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2nouha1, "toggled",
                    G_CALLBACK (on_checkbutton2nouha1_toggled),
                    NULL);
  g_signal_connect ((gpointer) afficherpaiementnouha, "clicked",
                    G_CALLBACK (on_afficherpaiementnouha_clicked),
                    NULL);
  g_signal_connect ((gpointer) calculernouha, "clicked",
                    G_CALLBACK (on_calculernouha_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestioncitoyen, gestioncitoyen, "gestioncitoyen");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, viewport9, "viewport9");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, treeview1nouha, "treeview1nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, Supprimeraficherr, "Supprimeraficherr");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label96, "label96");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, affichernouha, "affichernouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label95, "label95");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label652nouha, "label652nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, affichertous, "affichertous");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label101, "label101");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, affichercitoyen, "affichercitoyen");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, viewport8, "viewport8");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, idnouha, "idnouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbutton1nouha, "spinbutton1nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbutton2nouha, "spinbutton2nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbutton3nouha, "spinbutton3nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, nomnouha, "nomnouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, emailnouha, "emailnouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, cinnouha, "cinnouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, telephonenouha, "telephonenouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, matriculenouha, "matriculenouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, marquenouha, "marquenouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n12, "n12");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n4, "n4");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n3, "n3");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n2, "n2");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n1, "n1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label_statusnouha, "label_statusnouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, ajouternouha, "ajouternouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label75, "label75");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radiobutton2nouha, "radiobutton2nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radiobutton1nouha, "radiobutton1nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n8, "n8");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n5, "n5");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n7, "n7");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, checkbutton1nouha, "checkbutton1nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, checkbutton2nouha, "checkbutton2nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label37, "label37");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, combo1nouha, "combo1nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, combo2nouha, "combo2nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, titre1nouha, "titre1nouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, ajoutercitoyen, "ajoutercitoyen");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, scrolledwindow7, "scrolledwindow7");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, viewport7, "viewport7");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, idnouha1, "idnouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbutton1nouha1, "spinbutton1nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbutton2nouha1, "spinbutton2nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, spinbutton3nouha1, "spinbutton3nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, nomnouha1, "nomnouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, emailnouha1, "emailnouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, cinnouha1, "cinnouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, telephonenouha1, "telephonenouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, matriculenouha1, "matriculenouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label_statusnouha1, "label_statusnouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label84, "label84");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, n15, "n15");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label86, "label86");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label87, "label87");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label88, "label88");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label89, "label89");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label78, "label78");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label91, "label91");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label79, "label79");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label90, "label90");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label76, "label76");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, marquenouha1, "marquenouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, cherchernouha, "cherchernouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label94, "label94");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, modifiernouha, "modifiernouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label93, "label93");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, combo2nouha1, "combo2nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, combo1nouha1, "combo1nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label85, "label85");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label80, "label80");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radiobutton2nouha1, "radiobutton2nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, radiobutton1nouha1, "radiobutton1nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, checkbutton1nouha1, "checkbutton1nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, checkbutton2nouha1, "checkbutton2nouha1");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, viewport5, "viewport5");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, anneeavance, "anneeavance");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, treeviewpaiement, "treeviewpaiement");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, cinavance, "cinavance");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label72, "label72");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, afficherpaiementnouha, "afficherpaiementnouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label97, "label97");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, calculernouha, "calculernouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label98, "label98");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, prixnouha, "prixnouha");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, moisavance, "moisavance");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label70, "label70");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label100, "label100");
  GLADE_HOOKUP_OBJECT (gestioncitoyen, label15, "label15");

  return gestioncitoyen;
}

